FROM python:3.11-slim

WORKDIR /usr/app

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

ENTRYPOINT [ "bin/bash" ]
