name: 'retail_analytics'
version: '1.0.0'

profile: 'retail_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_analytics:
    +materialized: view
    +schema: analytics
    +tags: ['analytics']
    staging:
      +schema: staging
      +tags: ['staging']
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      +tags: ['intermediate']
    mart:
      +materialized: table
      +schema: mart
      +tags: ['mart']

seeds:
  retail_analytics:
    +schema: csv_input

tests:
  +severity: warn
  retail_analytics:
    +warn_if: ">10"
  mart:
    +severity: warn
  staging:
   +severity: warn
   +warn_if: ">10"
