name: 'retail_analytics'
version: '1.0.0'

profile: 'retail_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  retail_analytics:
    source:
      +materialized: view
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table

# seeds:
#   retail_analytics:
#     +schema: csv_input
