retail_analytics:
  outputs:
    dev:
      type: duckdb
      path: ../data/retail_analytics.duckdb
      threads: 1

    prod:
      type: duckdb
      path: ../data/retail_analytics_prod.duckdb
      threads: 4

  target: dev
